Handle iocard in verify

diff --git a/rootfs/skel/usr/bin/cartridge-verify b/rootfs/skel/usr/bin/cartridge-verify
--- a/rootfs/skel/usr/bin/cartridge-verify
+++ b/rootfs/skel/usr/bin/cartridge-verify
@@ -12,17 +12,26 @@ run() {
   fi
   if [[ -x "$EXE" ]]; then
     echo "[RIVOS] Unpacking rivlog..."
-    if ! unpack-rivlog </dev/mtdblock2 >/run/rivlog; then
+    if ! unpack-rivlog </dev/mtdblock2 >/run/eventlog; then
       >&2 echo "[RIVOS] Unable to unpack rivlog."
       return 1
     fi
     echo "[RIVOS] Running cartridge executable:" "$EXE" "$@"
+    if ! truncate -s 0 /run/iocard; then
+      >&2 echo "[RIVOS] Unable to create iocard."
+      return 1
+    fi
     BWRAPBOX_VERIFY_LIMITS=y \
-    BWRAPBOX_FLAGS="--setenv RIV_VERIFY_FD 3" \
-      bwrapbox-run "$EXE" "$@" 3</run/rivlog
+    BWRAPBOX_FLAGS="--setenv RIV_EVENTLOG_FD 3 --setenv RIV_IOCARD_FD 4" \
+      bwrapbox-run "$EXE" "$@" 3</run/eventlog 4<>/run/iocard
     STATUS=$?
+    sync # flush iocard
+    echo "==== BEGIN VERIFY OUTCARD ===="
+    cat /run/iocard
+    echo
+    echo "==== END VERIFY OUTCARD ===="
     echo "[RIVOS] Cartridge finished with status $STATUS"
-    rm -f /run/rivlog
+    rm -f /run/eventlog /run/iocard
   else
     >&2 echo "[RIVOS] No executable file found in cartridge."
     STATUS=1
